dbt_project_snow:
  outputs:
    dev:
      account: https://IEYKNZX-OO08997.snowflakecomputing.com
      database: DBT_PROJECT
      password: ArijitBittu@3329
      role: dev
      schema: SOURCE
      threads: 3
      type: snowflake
      user: arijitjana91
      warehouse: COMPUTE_WH
  target: dev
